### ISSUE TITLE
Installation fails at generating browser bundle 

### ISSUE THREAD

**Issue by jjwilliams** [strongloop/strong-mesh-client#40] opened 2015-10-17 07:05 UTC
When running npm install -g strongloop .... it fails in Windows 10, here is the relevant info:

> strong-mesh-client@1.6.3 install C:\Users\Josh\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client
> node proxy/build-client.js

unable to generate browser bundle: Cannot find module '..\..\..\..\..\strong-mesh-client\node_modules\browserify\node_modules\insert-module-globals\node_modules\is-buffer\index.js' from 'C:\Users\Josh\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\request\node_modules\http-signature\node_modules\assert-plus'

**Comment by barocsi** [comment] 2015-10-17 13:58
+1 here

**Comment by seza443** [comment] 2015-10-17 16:17
I had the same but after updating to the last version of nodejs, the error looks like 
```
> strong-mesh-client@1.6.3 install C:\Users\Tanguy\AppData\Roaming\npm\node_modu
les\strongloop\node_modules\strong-mesh-client
> node proxy/build-client.js

unable to generate browser bundle: Cannot find module '..\insert-module-globals\
node_modules\is-buffer\index.js' from 'C:\Users\Tanguy\AppData\Roaming\npm\node_
modules\strongloop\node_modules\assert-plus'
npm WARN install:strong-mesh-client@1.6.3 strong-mesh-client@1.6.3 install: `nod
e proxy/build-client.js`
npm WARN install:strong-mesh-client@1.6.3 Exit status 1
C:\Users\Tanguy\AppData\Roaming\npm
└── (empty)

npm ERR! code 1
```

**Comment by barocsi** [comment] 2015-10-17 17:44
Seems like [..]\node_modules\insert-module-globals\index.js generates a wrong path information at some point
>     'Buffer.isBuffer': function (file) {
        var relpath = getRelativePath(isbufferPath, file);
        return 'require(' + JSON.stringify(relpath) + ')';
    },

So now I am not able to install strongloop on my system.
Disclaimer: I know it's *unprofessional*, but what you can do **temporarily** as a workaround is to 

1. download strong-mesh-client-1.6.3 zip, 
2. extract, enter the dir, call npm install, 
3. it will run into the error above.  Prevent deleting files upon error when installing, or cancel (press ctrl-c) when installer runs node proxy/build-client.js point, or simply take out the install line from package.json
4. then edit the [..]node_modules\insert-module-globals\index.js file by replacing 'require(' + JSON.stringify(relpath) + ')'; with your absolute path to the is-buffer/index.js file that had been installed by the strong-mesh-client installing process at 2.
5. call $ node proxy/build-client.js manually, it will now install properly
6. now download the latest strongloop from github in zip extract to [your global node_modules folder]/strongloop
7. create a node_modules folder in your extracted strongloop dir, copy the strong-mesh-client modul  e there
7. call $npm install in the strongloop folder

**Comment by jjwilliams** [comment] 2015-10-17 18:47
Actually, I think just removing that relpath call and using JSON.stringify(isbufferPath) should work. Installed fine after that.

**Comment by rmg** [comment] 2015-10-17 18:52
Based on the timing of this, and a lack of any new releases of strong-mesh-client, substack/insert-module-globals#54 is at the top of my suspect list at the moment - it was published 10 hours before this issue was created.

**Comment by rmg** [comment] 2015-10-17 19:15
@jjwilliams @barocsi @seza443 @vnathalye you all appear to be having this problem on Windows only, is that correct? Could you also provide the output of `npm --version` and `node --version`?

**Comment by seza443** [comment] 2015-10-17 19:52
@rmg On Windows for me, yes.
```npm --version``` 3.3.8
```node --version``` v4.2.1

**Comment by barocsi** [comment] 2015-10-17 23:04
Windows 7, node v0.12.2, npm 3.3.8

**Comment by vnathalye** [comment] 2015-10-18 01:29
Windows 7
Node 4.0.0
npm 2.14.2

Side note: I had installed strongloop 3-4 days back. That time I did not get this error.
I started following the guide https://docs.strongloop.com/display/LB/Getting+started+with+LoopBack.
When I tried running `slc start` (as mentioned @ https://docs.strongloop.com/display/LB/Run+in+a+cluster) it went into infinite loop giving error "Cannot find module 'strong-debugger/package.json'", as well as starting and stopping node.exe processes in infinite loop.
Which led me to think that there might be some problem with my installation. So I uninstalled StrongLoop (using `npm uninstall -g strongloop`) and tried to reinstall it. Thats when I started getting above error.
HTH

**Comment by parshap** [comment] 2015-10-18 02:26
If someone can test this on Windows that'd be great. https://github.com/substack/insert-module-globals/pull/56

**Comment by seza443** [comment] 2015-10-18 09:46
I've changed the *index.js* file under *C:\Users\Tanguy\AppData\Roaming\npm\node_modules\insert-module-globals* with [your modifications](https://github.com/substack/insert-module-globals/pull/56) but I still have the same error.

Plus I've notice some red lines like:
```
  C:\Users\Tanguy\AppData\Roaming\npm\node_modules\strongloop\node_modules\node
  -inspector\node_modules\nan\nan.h(1731): note: le type est 'unknown-type'
C:\Users\Tanguy\AppData\Roaming\npm\node_modules\strongloop\node_modules\node-i
nspector\node_modules\nan\nan.h(1732): error C2065: 'ext' : identificateur non
déclaré [C:\Users\Tanguy\AppData\Roaming\npm\node_modules\strongloop\node_modul
es\node-inspector\node_modules\ws\build\validation.vcxproj]
C:\Users\Tanguy\AppData\Roaming\npm\node_modules\strongloop\node_modules\node-i
nspector\node_modules\nan\nan.h(1732): error C2227: la partie gauche de '->leng
th' doit pointer vers un type class/struct/union/générique [C:\Users\Tanguy\App
Data\Roaming\npm\node_modules\strongloop\node_modules\node-inspector\node_modul
es\ws\build\validation.vcxproj]
  C:\Users\Tanguy\AppData\Roaming\npm\node_modules\strongloop\node_modules\node
  -inspector\node_modules\nan\nan.h(1732): note: le type est 'unknown-type'
```
Are those warnings or errors ? Is it related ?

**Comment by rmg** [comment] 2015-10-18 17:46
The upstream fix has been released as insert-module-globals@6.6.2. In theory that means rerunning `npm install -g strongloop` should once again "just work". Can someone verify that on Windows?

**Comment by rmg** [comment] 2015-10-18 23:06
Looks like upstream fix in insert-module-globals v6.6.2 replaced the platform specific failure with a version specific failure, causing a regression on node-v0.10 on all platforms.

There is already a pull request to fix the new regression: substack/insert-module-globals#57

**Comment by ahmed-abdulmoniem** [comment] 2015-10-19 06:00
Any solution to this guys .. any workaround?

**Comment by parshap** [comment] 2015-10-19 10:18
The 0.10 issue should now be fixed in `insert-module-globals@6.6.3`. A fresh `npm install strongloop` should get this automatically. Give it a try and report back if there's still issues.

**Comment by vnathalye** [comment] 2015-10-19 11:27
Now I'm not getting the error related to **strong-mesh-client** and `strongloop` folder is also created under node_modules. 

But then there are (at least) 3 node-gyp errors for: **strong-debugger**, **utf-8-validate** & **bufferutil**. (and there are many other errors in between, like: syntax error; fatal error LNK1194; error C2065, C2039 etc).

So I'm not sure if I should call this installation as successful or failed. [As I had mentioned in my earlier post I was getting "Cannot find module 'strong-debugger/package.json'", while running `slc start`. So I assume I'll still get this error. Am I right?]

**Comment by seza443** [comment] 2015-10-19 13:30
Yup, ```npm install -g strongloop``` work for me!
Thanks you ;-)

**Comment by jjwilliams** [comment] 2015-10-19 13:53
Works like a charm, thanks!

**Comment by sam-github** [comment] 2015-10-19 16:26
> I was getting "Cannot find module 'strong-debugger/package.json'", while running slc start. So I assume I'll still get this error. Am I right?

@vnathalye You should not.

**Closed** 2015-10-19 16:26 UTC

**Comment by luncht1me** [comment] 2016-06-28 23:19
Install is failing again. For the exact same reason.
```
C:\Users\Guldan\Documents\GitHub\loopback>node -v
v6.2.2

C:\Users\Guldan\Documents\GitHub\loopback>npm -v
3.10.3
```

```
\\node_modules\\npm\\bin\\npm-cli.js" "install" "strong-mesh-client@latest"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! strong-mesh-client@2.0.2 install: `node proxy/build-client.js`
npm ERR! Exit status 1
```

**Comment by clok** [comment] 2017-03-06 18:31
This issue is happening again:

```
> strong-mesh-client@1.6.3 install /usr/local/lib/node_modules/strongloop/node_modules/strong-mesh-client
> node proxy/build-client.js

unable to generate browser bundle: Cannot find module 'regenerator' from '/usr/local/lib/node_modules/strongloop/node_modules/ajv/lib'
npm info lifecycle strong-mesh-client@1.6.3~install: Failed to exec install script
/usr/local/lib
`-- (empty)

npm ERR! Linux 4.9.12-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "strongloop@6.0.3"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strong-mesh-client@1.6.3 install script 'node proxy/build-client.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-mesh-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node proxy/build-client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-mesh-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-mesh-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
The command '/bin/sh -c npm install --global   strongloop@6.0.3   && npm cache clean' returned a non-zero code: 1
```

This is on Debian Jessie. Fresh install.

**Comment by rmg** [comment] 2017-03-06 21:44
If I clone this repo and run `npm install` it fails with the same error.

I _think_ I've tracked this down to a change in `request` that was made a few months ago (request/request#2480) but was only published a few days ago in request@2.80.0. Pinning the `request` dependency to `~2.79.0` allows the installation to finish successfully, which backs up the theory.

**Comment by rmg** [comment] 2017-03-07 00:18
Continuing on #53 since that issue is fresher and this one is closed.

**Comment by developermhayden** [comment] 2017-03-07 00:34
I fixed this issue using heroku/nodejs build pack and in the proc file

web: node server/server.js
