### ISSUE TITLE
Install Error - Cannot find module 'regenerator'

### ISSUE THREAD

**Issue by waltergammarota** [strongloop/strong-mesh-client#53] opened 2017-03-04 06:39 UTC
Hello I am facing this issue, I am using the heroku buildpack of strongloop, and I figured out there is a problem with this dependency. It was working fine, but since a few hours ago I can not install the library.

```
npm install strong-mesh-client@latest

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global ycssmin@1.0.1 should be installed with -g

strong-mesh-client@2.0.2 install /Users/walter/Documents/Work/Constelaciones/admin/api/node_modules/strong-mesh-client
 node proxy/build-client.js

(node:42655) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

unable to generate browser bundle: Cannot find module 'regenerator' from 'node_modules/ajv/lib'
```

Any clues?

**Comment by waltergammarota** [comment] 2017-03-04 06:40
@ritch

**Comment by clok** [comment] 2017-03-06 20:04
I am seeing this issue as well. It is breaking our builds.

**Comment by developermhayden** [comment] 2017-03-06 20:50
On my local development server, once I installed the following NPM packages, I was able to npm install strong-mesh-client

regenerator
Rodent
js-beautify

I'm going to add these packages to my package.json and try deploying again to Heroku.

**Comment by rmg** [comment] 2017-03-07 00:17
From https://github.com/strongloop/strong-mesh-client/issues/40#issuecomment-284542977:
> I _think_ I've tracked this down to a change in `request` that was made a few months ago (request/request#2480) but was only published a few days ago in `request@2.80.0`. Pinning the `request` dependency to `~2.79.0` allows the installation to finish successfully, which backs up the theory.

**Comment by rmg** [comment] 2017-03-07 01:22
@clok I've just released `strong-mesh-client@1.6.4` which should fix `npm install -g strongloop` for you. You may need to do `npm cache clear` to make sure the new version is seen.

**Comment by rmg** [comment] 2017-03-07 01:29
@waltergammarota @developermhayden `strong-mesh-client@1.6.4` should also fix the problem on Heroku, but I'm not sure how long it takes for the changes to propagate.

**Comment by rmg** [comment] 2017-03-07 02:13
Reported upstream as request/request#2585.

**Comment by svennam92** [comment] 2017-03-07 17:40
@rmg still running into failures with installing strong-mesh-client@1.6.4. FYI I'm doing an `npm install` on `strong-arc`:
```
> strong-mesh-client@1.6.4 install /Users/svennam/git/boilerplates/arcStarter/node_modules/strong-mesh-client
> node proxy/build-client.js

unable to generate browser bundle: Cannot find module 'regenerator' from '/Users/svennam/git/boilerplates/arcStarter/node_modules/ajv/lib'
arc@1.0.0 /Users/svennam/git/boilerplates/arcStarter
└── (empty)
```

**Comment by rmg** [comment] 2017-03-07 19:03
Submitted #57 with an updated fix.

**Comment by rmg** [comment] 2017-03-08 00:09
Released `strong-mesh-client@1.6.5` to fix this.

**Comment by svennam92** [comment] 2017-03-08 00:32
issue appears to be resolved with `1.6.5`. thanks @rmg!

**Comment by rmg** [comment] 2017-03-09 18:12
This should be working for you now, though I see from the original description that you were seeing this with `strong-mesh-client@2.0.2`. Was that just an attempt to reproduced the bug since that's what `latest` resolved to at the time? Or are you actually using a 2.x version of strong-mesh-client?

strong-mesh-client@2.x has not been fixed, but it is also unused and is no longer tagged as `latest`.

@waltergammarota could you please comment if you are still having problems, or close if not?

**Comment by rmg** [comment] 2017-03-10 18:01
I'm going to close this since it has been resolved as far as I can tell. @waltergammarota please re-open if you are still having issues.

**Closed by rmg** 2017-03-10 18:01 UTC
